### PR TITLE
feat: wip component with script setup and ts

### PR DESCRIPTION
**Pull request by dpschen**
I needed the component as script setup and wanted to share the result.

I basically just pasted the converted component. I didn't check build process etc. Will probably fail right now.

I deleted the manual types, since with `vue-tsc` it should be possible to extract the types automatically.

### CODE REVIEW

**Comment by ankurk91** [comment]
Heya,

Thanks, but i am already working on converting the code base to typescript.
https://github.com/ankurk91/vue-flatpickr-component/tree/typescript
I will pick some useful snippet from your pr too.

**Comment by dpschen** [comment]
All good :)
Just wanted to share, since I did the work either way.
Feel free to pick what ever makes sense to you.

**Comment by ankurk91** [comment]
Please test the version 11 (Full typescript)

```
npm install vue-flatpickr-component@^11
```

**Comment by ankurk91** [comment]
I was able to rewrite the component to typescript. I am closing the PR, thanks a lot.

**Pull request closed without merging**
