### PR TITLE
Added support to disable the input based on a prop.

### PR DESCRIPTION
**Pull request by otaviotech**
This changes allow us to bind a property called "disabled" to the component and it sets the "disabled" property on the binded flatpickr input thru a watched property.

### CODE REVIEW

**Comment by ankurk91** [comment]
Thanks for your contribution.


I am looking for a way to pass all attributes to visible input.
I will try to disable [inheritattrs](https://vuejs.org/v2/api/#inheritAttrs)
then by watching `$attrs` property, i can bind attributes to visible input.

**Comment by otaviotech** [comment]
Is there something I can help with this?

**Comment by ankurk91** [comment]
All attributes that is passed to component will be inherited by input element automatically and they are reactive too.
See,
https://jsfiddle.net/63kzdwLx/2942/

The only case when they are not reactive is when `altInput:true` in config.

**Comment by otaviotech** [comment]
I'm sorry for my mistakes, i didn't realize there is a contribute.md file.
For the dist folder, i used it because i needed for a project, but i was wrong trying to merge the master branch.

Thank you!

**Comment by matthewjmink** [comment]
This change does not solve the issue reported in #104. Do you have any thoughts on how to overcome this when an altInput is used? I've tried watching the `$vnode` property, but that does not seem to work. I am not aware of any ways to watch for changes to the class binding.

**Comment by ankurk91** [comment]
@matthewjmink 
According to [docs](https://vuejs.org/v2/api/#inheritAttrs)

> Note: this option does not affect class and style bindings.

One of the solution would be, if [Flatpickr](https://github.com/flatpickr/flatpickr) can use the existing input element rather creating new dynamically.
This way Vue.js can control both inputs.

**Comment by AdrianMrn** [comment]
Any progress on this one by any chance?

**Pull request closed without merging**
