### PR TITLE
Add update-on-blur property

### PR DESCRIPTION
**Pull request by notiv-nt**
Update value on blur. (tab)

## Before:

without

## After:

with

### CODE REVIEW

**Comment by ankurk91** [comment]
Can you create a js-fiddle demonstrating your issue,
https://jsfiddle.net/ankurk91/63kzdwLx/

Want to see why flatpickr itself does not emit `input` event

**Comment by notiv-nt** [comment]
What else is there to demonstrate? I attached gifs.

1. Focus input
2. Change date
3. Tab on next input
4. Value updated

**Comment by ankurk91** [comment]
I am looking for the config object.
How did you changed the date. Do you allow user to type into input field?
Did you press enter after input.

Please help me.

**Comment by notiv-nt** [comment]
## Html
```
<!-- Update value on blur (as is) -->
<flat-pickr
  v-model="post.startDate" 
  :config="dateConfig" 
  update-on-blur
></flat-pickr>

<!-- I must press enter to update value -->
<flat-pickr
  v-model="post.startDate" 
  :config="dateConfig" 
></flat-pickr>
```

## Js:
```
data: () => ({
  post: {
    startDate: new Date(),
  },

  dateConfig: {
    wrap: true,
    allowInput: true,
    enableTime: true,
    time_24hr: true,
    altFormat: 'd M Y H:i',
    altInput: true,
    dateFormat: 'Z',
  },
})
```

**Comment by ankurk91** [comment]
i don't think most developer would like to update the `v-model` on blur, your pull request is very specific  to your requirements.

It does not fix any existing issue, user is supposed to press enter to confirm the date after input.

**Pull request closed without merging**
