### PR TITLE
feat: add type declaration file

### LINKED ISSUE #202: Typescript declaration support
I'm using with nuxt/vue (lastest version) with typescript. Of course, when I import your module, it request the declaration file.
Can you write it for supporting the typescript project?

### PR DESCRIPTION
**Pull request by eliamartani**
Closes #202

### CODE REVIEW

**Comment by ankurk91** [comment]
Why do we need typescript compiler?
The `src` folder is not written in TS.

**Comment by eliamartani** [comment]
> Why do we need typescript compiler?
> The `src` folder is not written in TS.

Hi, good question. I added a script automation to update `index.d.ts` easily. That's the only reason why.

I can remove it if you prefer.

**Comment by ankurk91** [comment]
I am not sure if `tsc` can generate type definitions from `src` folder. `src` is plain js.

What do you think?

**Comment by eliamartani** [comment]
Actually it does, the `index.d.ts` was generated through the command `npm run build:types`.

In `tsconfig.json` there is a flag `allowJs: true` that triggers on js as well. Basically the `tsconfig.json` was set to allow this inspection on all js files.

**Comment by eliamartani** [comment]
I removed other files and kept only `index.d.ts`

**Comment by ankurk91** [comment]
These types are being generated from ES6 source code, it is hard to read and maintain such file.

I think we should either write types by hand or convert the source code to TS itself.

**Pull request closed without merging**
