### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by averichev**

### CODE REVIEW

**Comment by ankurk91** [comment]
Does this make any difference?
The existing code example was not working?

**Comment by averichev** [comment]
@ankurk91 old example not working for russian language. New example working for all locales, and warning from flatpickr not show

**Comment by ankurk91** [comment]
Okay, I will verify it soon

**Comment by ankurk91** [comment]
Flatpickr documentation is suggesting to the same as i am doing in my README.md

https://flatpickr.js.org/localization/

You example may also work, but my example is specific to the component instance.

The Russian locale file does exports the `Russian` object.
https://unpkg.com/flatpickr@4.5.7/dist/l10n/ru.js

**Pull request closed without merging**
