### PR TITLE
fix bug #20

### PR DESCRIPTION
**Pull request by angelowolf**

### CODE REVIEW

**Comment by ankurk91** [comment]
@angelowolf 
I was unable to fix that issue by applying your patch.
Can you describe how you PR fix that issue.

**Comment by angelowolf** [comment]
Hello the patch works fine, i try it myself.

Example:

` 
    <div>
        <flat-pickr :config="op" v-model="op.minDate"></flat-pickr>
        <flat-pickr :config="op2" v-model="op2.maxDate"></flat-pickr>
    </div>
`

and

`
     export default {
    data() {
      return {
        op: {minDate: null},
        op2: {maxDate: null}
      }
    },
    components: {
      flatPickr
    }
  }
`

**Comment by ankurk91** [comment]
@angelowolf
You have assigned config property to v-model, this is not the recommended way.
Flatpickr [configuration](https://chmln.github.io/flatpickr/options/) does not have any nested property so `deep` option in watch is useless here.

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-flatpickr-component/issues/20#issuecomment-326722848

**Pull request closed without merging**
